CREATE TABLE mensajes (
id_mensaje INT AUTO_INCREMENT PRIMARY KEY,
contenido_mensaje TEXT NOT NULL,
fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
id_usuario INT NOT NULL,
id_canal INT NOT NULL,
FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (id_canal) REFERENCES canales (id_canal) ON DELETE NO ACTION ON UPDATE NO ACTION
);